# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Order Tracking Page Pro"
client_id = "2d20e8e11bb0f54c316c6394ad8488d1"

application_url = "https://order-tracking-pro.netlify.app/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_fulfillments"

[auth]
redirect_urls = [
  "https://order-tracking-pro.onrender.com/callback",
  "https://order-tracking-pro.onrender.com/billing/callback"
]

[webhooks]
api_version = "2024-10"

# App lifecycle webhooks
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://order-tracking-pro.onrender.com/webhooks/app/uninstalled"

# Subscription webhooks for managed pricing
[[webhooks.subscriptions]]
topics = ["app_subscriptions/update"]
uri = "https://order-tracking-pro.onrender.com/webhooks/app/subscription"

# GDPR Compliance webhooks (MANDATORY for App Store)
[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://order-tracking-pro.onrender.com/webhooks/gdpr"

[pos]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#pos
embedded = false

# Extensions are automatically detected from the extensions/ directory

[build]
automatically_update_urls_on_dev = true 
dev_store_url = "https://iwanthisproduct.myshopify.com/"