# Learn more about configuring your theme app extension:
# https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started

api_version = "2024-07"

[[extensions]]
type = "theme"
name = "Order Tracking Widget"
handle = "tracking-widget"

[[extensions.blocks]]
type = "tracking-widget"
name = "Order Tracking Widget"